### ISSUE TITLE
todo for release

### ISSUE THREAD

**Issue by daejunpark** [runtimeverification/verified-smart-contracts#1]
Must:
- [x] spec-tmpl.k => module-tmpl.k
- [x] rule-tmpl.k => spec-tmpl.k
- [x] rename *.ini spec files
- [x] fix spec generation command
- [x] fix spec running command
- [x] fix erc20 running script
- [x] fix bihu running script
- [x] fix abstract-semantics.k
- [x] fix lemmas.md tangler issue
- [x] fix Makefile
- [x] remove bak directory
- [x] add sum-to-n.md
- [ ] add .PHONY target which allows to run the command even if accidently a file with the same name exists.
-
- [x] fix /erc20/README.md
- [x] drop edsl-notations.md and replace the links to it by kevm's one
- [x] fix the links in the end of /resources/edsl-spec.md
- [x] fix bihu report (two weeks time contracts)
- [x] rename all viper => vyper
- [x] fix "Viper" in erc20/vyper/vyper-erc20-spec.ini together with resources/lemmas.md

Optional:
- [ ] fix hobby/spec-diff.patch
- [ ] hobby erc20: explain approve function differences
- [ ] vyper erc20: add LLL file
-
- [ ] more explanation (why) for /resources/edsl-spec.md#program-specific-parameters
- [x] avoid duplication of proof running and kprove installation paragraphs
-
- [ ] add collectToken loop spec (not trusted)
-
- [ ] ~~spec-gen: support 'import' instead of postfix convention~~
- [ ] put prefix to collectToken spec.ini section names
-
- [ ] cleanup bihu lemmas
- [ ] cleanup lemmas, organize more
-
- [x] add ds-token spec
- [ ] add consensys erc20 spec
-
- [ ] ~~fix pdf icon~~
-
- [ ] prove both solc and remix compiled binaries
-
- [ ] make verification.md for bihu
-
- [ ] ~~delete /resources/edsl-notations.md~~
-
- [ ] consolidate verification methodology
- [x] delete scripts directory, moving gen-sepc.py to resources
- [x] move examples/sum-to-n
-
- [ ] fix https://github.com/kframework/evm-semantics/issues/145#event-1497045132
